name: flutter_blue_example
description: Demonstrates how to use the flutter_blue_plugin plugin.
publish_to: "none"

environment:
  sdk: '>=2.14.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue_plugin:
    path: ../

flutter:
  uses-material-design: true
