name: flutter_blue_plugin
description:
  Flutter plugin for connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS and Desktop
version: 0.9.0
homepage: https://github.com/Yongle-Fu/flutter_blue_plugin
#publish_to: https://pub.dev
#dart pub publish --server=https://pub.dartlang.org

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.1
  protobuf: ^2.0.1
  rxdart: ^0.27.3
  collection: ^1.15.0
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pauldemarco.flutter_blue_plugin
        pluginClass: FlutterBluePlugin
      ios:
        pluginClass: FlutterBluePlugin
      macos:
        pluginClass: FlutterBluePlugin
      windows:
        pluginClass: FlutterBluePlugin
